# Generated by Django 5.0.7 on 2024-07-21 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
